services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - musicbot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 60

  indexing:
    depends_on:
      redis:
        condition: service_healthy
    build: ./lavalink
    container_name: indexing
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=
    volumes:
      - ./lavalink:/ll/
    restart: "no"

  bot:
    depends_on:
      indexing:
        condition: service_completed_successfully
    build: ./bot
    container_name: bot
    environment:
      - BOT_TOKEN=

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      - MUSIC_DIRECTORY= # Music directory on local machine
      
      - CHANNEL_ID= # Voice channel ID

      - WEB_DASHBOARD_BASE_URL=http://localhost:8080 # Web dashboard base URL. Make sure to change it to your domain.
    networks:
      - musicbot-network

  web:
    depends_on:
      indexing:
        condition: service_completed_successfully
    build: ./web
    container_name: web
    environment:
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - DISCORD_CALLBACK_URL=http://localhost:8080/auth/cb # Discord callback URL. You need to add /auth/cb at the end.
      - DISCORD_GUILD_ID= # Discord guild ID
      - SESSION_SECRET= # Session secret
    networks:
      - musicbot-network
    ports:
      - "8080:8080"

  lavalink:
    image: ghcr.io/lavalink-devs/lavalink:4
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
    volumes:
      - ./lavalink/:/opt/Lavalink/
    expose:
      - 2333
    networks:
      - musicbot-network

networks:
  musicbot-network:
    driver: bridge