services:
  redis:
    image: redis:latest
    container_name: redis
    networks:
      - musicbot-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 5s
      retries: 60

  lavalink:
    image: fredboat/lavalink:4.0-alpine
    container_name: lavalink
    restart: unless-stopped
    environment:
      - _JAVA_OPTIONS=-Xmx6G
      - SERVER_PORT=2333
    volumes:
      - ./lavalink/:/opt/Lavalink/
    expose:
      - 2333
    networks:
      - musicbot-network

  indexing:
    depends_on:
      redis:
        condition: service_healthy
    build: ./lavalink
    container_name: indexing
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    volumes:
      - ./lavalink/music/:/music
    networks:
      - musicbot-network
    restart: "no"

  bot:
    depends_on:
      indexing:
        condition: service_completed_successfully
    build: ./bot
    container_name: bot
    environment:
      - DISCORD_BOT_TOKEN=${BOT_TOKEN}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - CHANNEL_ID=${CHANNEL_ID}
      - WEB_DASHBOARD_BASE_URL=${WEB_DASHBOARD_BASE_URL}
    networks:
      - musicbot-network

  web:
    depends_on:
      indexing:
        condition: service_completed_successfully
    build: ./web
    container_name: web
    environment:
      - DISCORD_CLIENT_ID=${DISCORD_CLIENT_ID}
      - DISCORD_CLIENT_SECRET=${DISCORD_CLIENT_SECRET}
      - DISCORD_CALLBACK_URL=${DISCORD_CALLBACK_URL}
      - DISCORD_GUILD_ID=${DISCORD_GUILD_ID}
      - SESSION_SECRET=${SESSION_SECRET}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    networks:
      - musicbot-network
    ports:
      - "${PORT}:8080"

networks:
  musicbot-network:
    driver: bridge