services:
  bot:
    build: ./bot
    container_name: bot
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      - MUSIC_DIRECTORY= # Music directory on local machine
      
      - CHANNEL_ID= # Voice channel ID
    networks:
      - musicbot-network

  web:
    build: ./web
    container_name: web
    depends_on:
      - bot
    networks:
      - musicbot-network
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - musicbot-network

networks:
  musicbot-network:
    driver: bridge