services:
  bot:
    build: ./bot
    container_name: bot
    depends_on:
      - redis
    environment:
      - BOT_TOKEN=

      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=

      - MUSIC_DIRECTORY= # Music directory on local machine
      
      - CHANNEL_ID= # Voice channel ID

      - WEB_DASHBOARD_BASE_URL=http://localhost:8080 # Web dashboard base URL. Make sure to change it to your domain.
    networks:
      - musicbot-network

  web:
    build: ./web
    container_name: web
    depends_on:
      - bot
    environment:
      - DISCORD_CLIENT_ID=
      - DISCORD_CLIENT_SECRET=
      - DISCORD_CALLBACK_URL=http://localhost:8080/auth/cb # Discord callback URL. You need to add /auth/cb at the end.
      - DISCORD_GUILD_ID= # Discord guild ID
      - SESSION_SECRET= # Session secret
    networks:
      - musicbot-network
    ports:
      - "8080:8080"

  redis:
    image: redis:latest
    container_name: redis
    networks:
      - musicbot-network

networks:
  musicbot-network:
    driver: bridge